### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by paulirish** [jonrimmer/are-we-componentized-yet#1]
this thing is super hard to find

@ebidel and i were looking for a while with search terms like
- web components status
- web components dashboard
- are web components ready yet

etc.. and didnt find it.

so many we can drop in some more terms to the page so its more findable?

**Comment by ebidel** [comment]
+1000 :)

**Comment by jonrimmer** [comment]
Sounds like a bug in your search engine :-P

But seriously, you're right. I need to add in some more keywords / explanation + update everything with the latest polymer-shaped developments. I'll get on it.

**Comment by paulirish** [comment]
dope!

**Comment by jonrimmer** [comment]
Fixed by cc5cf7e46fb57c14ea6268bfe99fec3785e914c4
