### ISSUE TITLE
At least Safari information inaccurate

### ISSUE THREAD

**Issue by JoernT** [jonrimmer/are-we-componentized-yet#12]
Hi,
maybe time to update the matrix...

x-tags for instance claims to be compatible with Safari and IE and some mobile browsers. My own tests with simple custom element creation shows no problem in Safari 7 / osx - it just works. Even if it supports only a smaller subset of the whole spec it's worth mentioning. At least x-tags feels stable in contrast to Polymer.

**Comment by jonrimmer** [comment]
Hi @JoernT

The purpose of the site is to track the native implementation of the various web components features within each browser, not whether a compatible polyfill exists, although there is a separate polyfill column that tracks whether a polyfill exists at all.

A matrix that tracked the support of the polyfills for different browsers would be interesting, but it is outside the scope of Are We Componentized Yet. The Polymer project maintains such a compatibility matrix here: http://www.polymer-project.org/resources/compatibility.html and the X-Tag project has a browser compatibility section on their homepage: http://www.x-tags.org/ .

**Comment by JoernT** [comment]
Ah, ok - thanks for the explanation - if one reads thoroughly one might get it ;)

I'm a big fan of web components and actually plan a bigger project using them - i'm a bit worried that the shyness of the developers of the polyfills (esp. Polymer) might drive people away as they don't get tired to label it as 'alpha' 'not ready' etc. I very well understand that (being an Open Source developer myself) but i can really get counter-productive if you'd like to promote the technology - one day you have to be bold and declare things as stable (even if it's just a subset) otherwise you'll be forgotten and not taken seriously.

Let's face it - nobody can guarantee that all relevant browsers will implement the whole spec (or at all) - that's why polyfills are so important. This happened too often with W3C specs but does not always mean that the technologies aren't used in production. 

Sorry for going a bit off-topic here ;)

**Comment by astericky** [comment]
Hi guys I too am a big fan of web components every since I've heard of the spec. I don't understand why we aren't exerting more pressure on Safari to implement them or at least explain why they haven't been implemented. Addy recently announced full support for Web Components in Chrome 36. https://twitter.com/addyosmani/status/489490560869490688
