### ISSUE TITLE
Bosonic library should be mentioned

### ISSUE THREAD

**Issue by goldoraf** [jonrimmer/are-we-componentized-yet#19]
Hi!

There's a third library that allows to build web components: [Bosonic](http://bosonic.github.io).

It uses some of Polymer's polyfills for now, but the next version will propose a more lightweight platform.

Would you like a PR or do you prefer to rewrite the paragraph yourself ?

**Comment by jonrimmer** [comment]
Thanks for the heads up! I have reworked the Polyfills section and included some info on Bosonic.
