### ISSUE TITLE
Links to template specs are out of date

### ISSUE THREAD

**Issue by JeniT** [jonrimmer/are-we-componentized-yet#20]
The links you have to the "Template" specs are out of date. The one to GitHub results in a 404 and the one to W3C Working Draft is basically empty except for a status message that says "Work on this document has been discontinued and it should not be referenced or used as a basis for implementation". I'm not up to date enough to know where the new docs might be, if they even exist...

**Comment by jonrimmer** [comment]
Thanks for the heads up! Since it looks like the explainer spec has been discontinued, I've removed the column from the table. I've updated the templates spec to point to the right URL.
