### ISSUE TITLE
html templates editors draft is a dead link

### ISSUE THREAD

**Issue by cpoole** [jonrimmer/are-we-componentized-yet#23]
http://w3c.github.io/webcomponents/spec/templates/ is a 404.
apparently this has been officially integrated into html5 and the link is http://www.w3.org/TR/html5/scripting-1.html#the-template-element

**Comment by cpoole** [comment]
also might be worth adding these links to the ie section:
shadow dom: https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6263785-shadow-dom-unprefixed
html imports: https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6261318-html-imports
custom elements: https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6261298-custom-elements
html templates: https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6261273-template-element

We are probably stuck with ie for a long time, it cant hurt to have people vote on the

**Comment by zenorocha** [comment]
We've been pointing webcomponents.org users to this link:

https://html.spec.whatwg.org/multipage/scripting.html#the-template-element

**Comment by cpoole** [comment]
hah, same thing I just added to my comment

**Comment by jonrimmer** [comment]
Yikes, sorry this took so long to address. Thanks for the heads up guys. Fixed by a3db34f.
