### ISSUE TITLE
Should the Templates box for IE be changed to "in progress" (yellow)?

### ISSUE THREAD

**Issue by waldyrious** [jonrimmer/are-we-componentized-yet#28]
It's marked in Uservoice as "[Working on it](https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6261273-template-element)" and in status.modern.ie as "[In development](https://status.modern.ie/templateelement)".

Also (and perhaps more importantly), from [the announcement in the Edge dev blog](https://blogs.windows.com/msedgedev/2015/07/15/microsoft-edge-and-web-components/):

> today we’re excited to announce that we’re beginning development on the HTML Template element

**Comment by waldyrious** [comment]
btw the other three have all been marked "on the backlog" in UserVoice since yesterday :smile:

**Comment by jonrimmer** [comment]
Thanks, updated!
