### ISSUE TITLE
Should the Template box for MS Edge be changed to "Stable" Green?

### ISSUE THREAD

**Issue by smasher164** [jonrimmer/are-we-componentized-yet#29]
(11-12-2015) According to the [**Uservoice page for the Template Element**](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6261273-template-element)

> The template element shipped in EdgeHTML 13 as part of the Microsoft Edge version included in Windows 10 build 10586 (November 2015).

This feature is now marked with the status **`BOOM! IT'S DONE.`**

**Comment by zenorocha** [comment]
Updated on webcomponents.org! https://github.com/webcomponents/webcomponents.github.io/commit/91259fcac64b32b7a631694ac62cb556975b5cc0

Thanks for reporting @smasher164 ;)
