### ISSUE TITLE
x-tags by Mozilla? or Microsoft?

### ISSUE THREAD

**Issue by dalvarezmartinez1** [jonrimmer/are-we-componentized-yet#32]
On their webpage: http://x-tag.github.io/ it clearly says it's supported by Microsoft. Was it created by Mozilla? Should this be corrected?

**Comment by bauerj** [comment]
The original author is[ now working at Microsoft](https://twitter.com/csuwildcat/status/666692606311555072?s=09).

**Comment by jonrimmer** [comment]
Thanks for reporting this. Sorry I never got around to addressing it. I've decided to retire the site rather than leave it in a somewhat outdated state.
