### ISSUE TITLE
Need some opinion on wechat browser

### ISSUE THREAD

**Issue by jamesbondo** [jonrimmer/are-we-componentized-yet#35]
Do you know anything about the only popular app in China called Wechat? 
It has it's own browser embedded, which is supposed to be very powerful, but I'm wondering if you would like to take a took and give us some review. 
I'm a Chinese, so I can help you to translate it after you are done. 
http://www.wechat.com/en/download.html
The security is a bit of annoying to some foreigners, but if you can bare with it, it's actually pretty neat in consideration of security.

**Comment by jonrimmer** [comment]
I don't do browser testing myself to establish whether particular browsers support web component features. Instead I rely on data from sites like [caniuse](caniuse.com) and browser vendor's own reporting of their supported features and development plans, for example through sites like [chromestatus.com](https://www.chromestatus.com/features). If Tenecent publish something like this for WeChat, I could link to it. As far as I can tell, WeChat [user agent string](https://gist.github.com/wjp2013/fff34c063cf0cf227d65) suggests it is a version of WebKit, so its support should roughly match what is reported for Safari.
