### ISSUE TITLE
Webkit tech preview 18 has custom elements

### ISSUE THREAD

**Issue by thepian** [jonrimmer/are-we-componentized-yet#39]
So they should come in safari 11 next summer

**Comment by bgotink** [comment]
Safari 10.1 (currently in beta) includes custom elements: [What's new in Safari 10.1](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html)

**Comment by jonrimmer** [comment]
👍
