### ISSUE TITLE
Update needed for X-Tag description

### ISSUE THREAD

**Issue by csuwildcat** [jonrimmer/are-we-componentized-yet#4]
X-Tag and Polymer now share the same set of polyfills, and are similarly featured, but have different high-level sugaring opinions. We chose not to include the Shadow DOM polyfill because of various limitations and performance concerns that any attempt to polyfill that particular spec brings with it. See here for more details: http://www.x-tags.org/blog

**Comment by jonrimmer** [comment]
Thanks for the heads up! I have updated the description and included a quote from the X-Tag blog in b36eee38856504256933eb7392fa7ffb4cf4160b
