### ISSUE TITLE
customelements.io has expired

### ISSUE THREAD

**Issue by peterennis** [jonrimmer/are-we-componentized-yet#41]
![capture973](https://user-images.githubusercontent.com/140737/29680942-02076aaa-88bb-11e7-9391-be78cdda2212.png)

![capture974](https://user-images.githubusercontent.com/140737/29680947-0857294a-88bb-11e7-8881-1e0b132e88d8.png)

**Comment by jonrimmer** [comment]
Thanks for letting me know. After thinking a bit, I've decided to retire AWCY, as there are other, better sources of information about web components available now, and, as this issue demonstrates, I don't really have the time or interest to keep the site up-to-date as  a useful source.
