### ISSUE TITLE
Update on Safari status

### ISSUE THREAD

**Issue by mkozlows** [jonrimmer/are-we-componentized-yet#9]
At least some tentative development is starting on WebKit:

https://lists.webkit.org/pipermail/webkit-dev/2014-February/026251.html

**Comment by jonrimmer** [comment]
Thanks. Yeah, I did see this myself, but I've not been able to find any evidence that this branch actually exists yet. There is nothing in https://trac.webkit.org/browser/branches , and no tracking bugs for the work in the WebKit bugzilla. I'm holding off updating about it until I see some more concrete signs of progress.

**Comment by slightlyoff** [comment]
https://bugs.webkit.org/show_bug.cgi?id=148695

**Comment by jonrimmer** [comment]
:+1: Cheers!
